const Data = [
    // {
    //     key: "C",
    //     i: "C",
    //     i: "Cm",
    //     i: "C#",
    //     i: "C#m",
    //     i: "Db",
    //     i: "Dbm",
    //     i: "D",
    //     i: "Dm",
    //     i: "D#",
    //     i: "D#m",
    //     i: "Eb",
    //     i: "Ebm",
    //     i: "E",
    //     i: "Em",
    //     i: "F",
    //     i: "Fm",
    //     i: "F#",
    //     i: "F#m",
    //     i: "Gb",
    //     i: "Gbm",
    //     i: "G",
    //     i: "Gm",
    //     i: "G#",
    //     i: "G#m",
    //     i: "Ab",
    //     i: "Abm",
    //     i: "A",
    //     i: "Am",
    //     i: "A#",
    //     i: "A#m",
    //     i: "Bb",
    //     i: "Bbm",
    //     i: "B",
    //     i: "Bm"
    // },
    {
        // key: "1",//
        key: "C",
        i: "C",
        ii: "Cm",
        iii: "C#",
        iv: "C#m",
        v: "Db",
        vi: "Dbm",
        vii: "D",
        viii: "Dm",
        ix: "D#",
        x: "D#m",
        xi: "Eb",
        xii: "Ebm",
        xiii: "E",
        xiv: "Em",
        xv: "F",
        xvi: "Fm",
        xvii: "F#",
        xviii: "F#m",
        xix: "Gb",
        xx: "Gbm",
        xxi: "G",
        xxii: "Gm",
        xxiii: "G#",
        xxiv: "G#m",
        xxv: "Ab",
        xxvi: "Abm",
        xxvii: "A",
        xxviii: "Am",
        xxiv: "A#",
        xxx: "A#m",
        xxxi: "Bb",
        xxxii: "Bbm",
        xxxiii: "B",
        xxxiv: "Bm"
    },
    {
        // key: "2"//
        key: "C#",
        i: "C#",
        ii: "C#m",
        iii: "Db",
        iv: "Dbm",
        v: "D",
        vi: "Dm",
        vii: "D#",
        viii: "D#m",
        ix: "Eb",
        x: "Ebm",
        xi: "E",
        xii: "Em",
        xiii: "F",
        xiv: "Fm",
        xv: "F#",
        xvi: "F#m",
        xvii: "Gb",
        xviii: "Gbm",
        xix: "G",
        xx: "Gm",
        xxi: "G#",
        xxii: "G#m",
        xxiii: "Ab",
        xxiv: "Abm",
        xxv: "A",
        xxvi: "Am",
        xxvii: "A#",
        xxviii: "A#m",
        xxix: "Bb",
        xxx: "Bbm",
        xxxi: "B",
        xxxii: "Bm",
        xxxiii: "C",
        xxxiv: "Cm"
    },
    {
        // key: "3"//
        key: "Db",

        i: "Db",
        ii: "Dbm",
        iii: "D",
        iv: "Dm",
        v: "D#",
        vi: "D#m",
        vii: "Eb",
        viii: "Ebm",
        ix: "E",
        x: "Em",
        xi: "F",
        xii: "Fm",
        xiii: "F#",
        xix: "F#m",
        xx: "Gb",
        xvi: "Gbm",
        xvii: "G",
        xviii: "Gm",
        xiv: "G#",
        xx: "G#m",
        xxi: "Ab",
        xxii: "Abm",
        xxiii: "A",
        xxiv: "Am",
        xxv: "A#",
        xxvi: "A#m",
        xxvii: "Bb",
        xxviii: "Bbm",
        xxix: "B",
        xxx: "Bm",
        xxxi: "C",
        xxxii: "Cm",
        xxxiii: "C#",
        xxxiv: "C#m"
    },
    {
        // key: "4"//
        key: "D",

        i: "D",
        ii: "Dm",
        iii: "D#",
        iv: "D#m",
        x: "Eb",
        vi: "Ebm",
        vii: "E",
        viii: "Em",
        ix: "F",
        x: "Fm",
        xi: "F#",
        xii: "F#m",
        xiii: "Gb",
        xiv: "Gbm",
        xv: "G",
        xvi: "Gm",
        xvii: "G#",
        xviii: "G#m",
        xix: "Ab",
        xx: "Abm",
        xxi: "A",
        xxii: "Am",
        xxiii: "A#",
        xxiv: "A#m",
        xxv: "Bb",
        xxvi: "Bbm",
        xxvii: "B",
        xxviii: "Bm",
        xxix: "C",
        xxx: "Cm",
        xxxi: "C#",
        xxxii: "C#m",
        xxxiii: "Db",
        xxxiv: "Dbm"
    },
    {
        // key: "5"//
        key: "D#",

        i: "D#",
        ii: "D#m",
        iii: "Eb",
        iv: "Ebm",
        x: "E",
        vi: "Em",
        vii: "F",
        viii: "Fm",
        ix: "F#",
        x: "F#m",
        xi: "Gb",
        xii: "Gbm",
        xiii: "G",
        xiv: "Gm",
        xv: "G#",
        xvi: "G#m",
        xvii: "Ab",
        xviii: "Abm",
        xix: "A",
        xx: "Am",
        xxi: "A#",
        xxii: "A#m",
        xxiii: "Bb",
        xxiv: "Bbm",
        xxv: "B",
        xxvi: "Bm",
        xxvii: "C",
        xxviii: "Cm",
        xxix: "C#",
        xxx: "C#m",
        xxxi: "Db",
        xxxii: "Dbm",
        xxxiii: "D",
        xxxiv: "Dm",
    },
    {
        // key: "6"//
        key: "Eb",

        i: "Eb",
        ii: "Ebm",
        iii: "E",
        iv: "Em",
        x: "F",
        vi: "Fm",
        vii: "F#",
        viii: "F#m",
        ix: "Gb",
        x: "Gbm",
        xi: "G",
        xii: "Gm",
        xiii: "G#",
        xiv: "G#m",
        xv: "Ab",
        xvi: "Abm",
        xvii: "A",
        xviii: "Am",
        xix: "A#",
        xx: "A#m",
        xxi: "Bb",
        xxii: "Bbm",
        xxiii: "B",
        xxiv: "Bm",
        xxv: "C",
        xxvi: "Cm",
        xxvii: "C#",
        xxviii: "C#m",
        xxix: "Db",
        xxx: "Dbm",
        xxxi: "D",
        xxxii: "Dm",
        xxxiii: "D#",
        xxxiv: "D#m",
    },
    {
        // key: "7"//
        key: "E",
        i: "E",
        ii: "Em",
        iii: "F",
        iv: "Fm",
        x: "F#",
        vi: "F#m",
        vii: "Gb",
        viii: "Gbm",
        ix: "G",
        x: "Gm",
        xi: "G#",
        xii: "G#m",
        xiii: "Ab",
        xiv: "Abm",
        xv: "A",
        xvi: "Am",
        xvii: "A#",
        xviii: "A#m",
        xix: "Bb",
        xx: "Bbm",
        xxi: "B",
        xxii: "Bm",
        xxiii: "C",
        xxiv: "Cm",
        xxv: "C#",
        xxvi: "C#m",
        xxvii: "Db",
        xxviii: "Dbm",
        xxix: "D",
        xxx: "Dm",
        xxxi: "D#",
        xxxii: "D#m",
        xxxiii: "Eb",
        xxxiv: "Ebm"

    },
    {
        // key: "8"//
        key: "F",
        i: "F",
        ii: "Fm",
        iii: "F#",
        iv: "F#m",
        x: "Gb",
        vi: "Gbm",
        vii: "G",
        viii: "Gm",
        ix: "G#",
        x: "G#m",
        xi: "Ab",
        xii: "Abm",
        xiii: "A",
        xiv: "Am",
        xv: "A#",
        xvi: "A#m",
        xvii: "Bb",
        xviii: "Bbm",
        xix: "B",
        xx: "Bm",
        xxi: "C",
        xxii: "Cm",
        xxiii: "C#",
        xxiv: "C#m",
        xxv: "Db",
        xxvi: "Dbm",
        xxvii: "D",
        xxviii: "Dm",
        xxix: "D#",
        xxx: "D#m",
        xxxi: "Eb",
        xxxii: "Ebm",
        xxxiii: "E",
        xxxiv: "Em"

    },
    {
        // key: "9"//
        key: "F#",
        
        i: "Fm",
        ii: "F#",
        iii: "F#m",
        iv: "Gb",
        x: "Gbm",
        vi: "G",
        vii: "Gm",
        viii: "G#",
        ix: "G#m",
        x: "Ab",
        xi: "Abm",
        xii: "A",
        xiii: "Am",
        xiv: "A#",
        xv: "A#m",
        xvi: "Bb",
        xvii: "Bbm",
        xviii: "B",
        xix: "Bm",
        xx: "C",
        xxi: "Cm",
        xxii: "C#",
        xxiii: "C#m",
        xxiv: "Db",
        xxv: "Dbm",
        xxvi: "D",
        xxvii: "Dm",
        xxviii: "D#",
        xxix: "D#m",
        xxx: "Eb",
        xxxi: "Ebm",
        xxxii: "E",
        xxxiii: "Em",
        xxxiv: "F",
    },
    {
        // key: "10"//
        key: "Gb",

        i: "Gb",
        ii: "Gbm",
        iii: "G",
        iv: "Gm",
        x: "G#",
        vi: "G#m",
        vii: "Ab",
        viii: "Abm",
        ix: "A",
        x: "Am",
        xi: "A#",
        xii: "A#m",
        xiii: "Bb",
        xiv: "Bbm",
        xv: "B",
        xvi: "Bm",
        xvii: "C",
        xviii: "Cm",
        xix: "C#",
        xx: "C#m",
        xxi: "Db",
        xxii: "Dbm",
        xxiii: "D",
        xxiv: "Dm",
        xxv: "D#",
        xxvi: "D#m",
        xxvii: "Eb",
        xxviii: "Ebm",
        xxix: "E",
        xxx: "Em",
        xxxi: "F",
        xxxii: "Fm",
        xxxiii: "F#",
        xxxiv: "F#m"
    },
    {
        // key: "11"//
        key: "G",
        i: "G",
        ii: "Gm",
        iii: "G#",
        iv: "G#m",
        x: "Ab",
        vi: "Abm",
        vii: "A",
        viii: "Am",
        ix: "A#",
        x: "A#m",
        xi: "Bb",
        xii: "Bbm",
        xiii: "B",
        xiv: "Bm",
        xv: "C",
        xvi: "Cm",
        xvii: "C#",
        xviii: "C#m",
        xix: "Db",
        xx: "Dbm",
        xxi: "D",
        xxii: "Dm",
        xxiii: "D#",
        xxiv: "D#m",
        xxv: "Eb",
        xxvi: "Ebm",
        xxvii: "E",
        xxviii: "Em",
        xxix: "F",
        xxx: "Fm",
        xxxi: "F#",
        xxxii: "F#m",
        xxxiii: "Gb",
        xxxiv: "Gbm",
    },
    {
        // key: "12"//
        key: "G#",
        i: "G#",
        ii: "G#m",
        iii: "Ab",
        iv: "Abm",
        x: "A",
        vi: "Am",
        vii: "A#",
        viii: "A#m",
        ix: "Bb",
        x: "Bbm",
        xi: "B",
        xii: "Bm",
        xiii: "C",
        xiv: "Cm",
        xv: "C#",
        xvi: "C#m",
        xvii: "Db",
        xviii: "Dbm",
        xix: "D",
        xx: "Dm",
        xxi: "D#",
        xxii: "D#m",
        xxiii: "Eb",
        xxiv: "Ebm",
        xxv: "E",
        xxvi: "Em",
        xxvii: "F",
        xxviii: "Fm",
        xxix: "F#",
        xxx: "F#m",
        xxxi: "Gb",
        xxxii: "Gbm",
        xxxiii: "G",
        xxxiv: "Gm",
    },
    {
        // key: "13"//
        key: "Ab",
        i: "Ab",
        ii: "Abm",
        iii: "A",
        iv: "Am",
        x: "A#",
        vi: "A#m",
        vii: "Bb",
        viii: "Bbm",
        ix: "B",
        x: "Bm",
        xi: "C",
        xii: "Cm",
        xiii: "C#",
        xiv: "C#m",
        xv: "Db",
        xvi: "Dbm",
        xvii: "D",
        xviii: "Dm",
        xix: "D#",
        xx: "D#m",
        xxi: "Eb",
        xxii: "Ebm",
        xxiii: "E",
        xxiv: "Em",
        xxv: "F",
        xxvi: "Fm",
        xxvii: "F#",
        xxviii: "F#m",
        xxix: "Gb",
        xxx: "Gbm",
        xxxi: "G",
        xxxii: "Gm",
        xxxiii: "G#",
        xxxiv: "G#m",
    },
    {
        // key: "14"//
        key: "A",
        i: "A",
        ii: "Am",
        iii: "A#",
        iv: "A#m",
        x: "Bb",
        vi: "Bbm",
        vii: "B",
        viii: "Bm",
        ix: "C",
        x: "Cm",
        xi: "C#",
        xii: "C#m",
        xiii: "Db",
        xiv: "Dbm",
        xv: "D",
        xvi: "Dm",
        xvii: "D#",
        xviii: "D#m",
        xix: "Eb",
        xx: "Ebm",
        xxi: "E",
        xxii: "Em",
        xxiii: "F",
        xxiv: "Fm",
        xxv: "F#",
        xxvi: "F#m",
        xxvii: "Gb",
        xxviii: "Gbm",
        xxix: "G",
        xxx: "Gm",
        xxxi: "G#",
        xxxii: "G#m",
        xxxiii: "Ab",
        xxxiv: "Abm",
    },
    {
        // key: "15"//
        key: "A#",
        i: "A#",
        ii: "A#m",
        iii: "Bb",
        iv: "Bbm",
        x: "B",
        vi: "Bm",
        vii: "C",
        viii: "Cm",
        ix: "C#",
        x: "C#m",
        xi: "Db",
        xii: "Dbm",
        xiii: "D",
        xiv: "Dm",
        xv: "D#",
        xvi: "D#m",
        xvii: "Eb",
        xviii: "Ebm",
        xix: "E",
        xx: "Em",
        xxi: "F",
        xxii: "Fm",
        xxiii: "F#",
        xxiv: "F#m",
        xxv: "Gb",
        xxvi: "Gbm",
        xxvii: "G",
        xxviii: "Gm",
        xxix: "G#",
        xxx: "G#m",
        xxxi: "Ab",
        xxxii: "Abm",
        xxxiii: "A",
        xxxiv: "Am",
    },
    {
        // key: "16"//
        key: "Bb",
        i: "Bb",
        ii: "Bbm",
        iii: "B",
        iv: "Bm",
        x: "C",
        vi: "Cm",
        vii: "C#",
        viii: "C#m",
        ix: "Db",
        x: "Dbm",
        xi: "D",
        xii: "Dm",
        xiii: "D#",
        xiv: "D#m",
        xv: "Eb",
        xvi: "Ebm",
        xvii: "E",
        xviii: "Em",
        xix: "F",
        xx: "Fm",
        xxi: "F#",
        xxii: "F#m",
        xxiii: "Gb",
        xxiv: "Gbm",
        xxv: "G",
        xxvi: "Gm",
        xxvii: "G#",
        xxviii: "G#m",
        xxix: "Ab",
        xxx: "Abm",
        xxxi: "A",
        xxxii: "Am",
        xxxiii: "A#",
        xxxiv: "A#m",
    },
    {
        // key: "17"//
        key: "B",
        i: "B",
        ii: "Bm",
        iii: "C",
        vi: "Cm",
        v: "C#",
        vi: "C#m",
        vii: "Db",
        viii: "Dbm",
        ix: "D",
        x: "Dm",
        xi: "D#",
        xii: "D#m",
        xiii: "Eb",
        xiv: "Ebm",
        xv: "E",
        xvi: "Em",
        xvii: "F",
        xviii: "Fm",
        xiv: "F#",
        xx: "F#m",
        xxi: "Gb",
        xxii: "Gbm",
        xxiii: "G",
        xxiv: "Gm",
        xxv: "G#",
        xxvi: "G#m",
        xxvii: "Ab",
        xxviii: "Abm",
        xxix: "A",
        xxx: "Am",
        xxxi: "A#",
        xxxii: "A#m",
        xxxii: "Bb",
        xxxiv: "Bbm",
    },
    

]

export default Data;